version: '2'

services:
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ezdataflow
      MYSQL_USER: ezdataflow
      MYSQL_PASSWORD: ezdataflow
    ports:
      - "3306:3306"
