CityItemUpdateInput:
    type: input-object
    config:
        fields:
            nom:
                type: String
            codesPostaux:
                type: String
            population:
                type: Int
            codeRegion:
                type: String
            codeDepartement:
                type: String
