# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    eztags.site.tag_view.pagelayout: 'themes/site/pagelayout.html.twig'
    eztags.site.tag_view.template: 'themes/site/full/tag_view.html.twig'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Migrations,Tests,Listener}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        tags: ['controller.service_arguments']


    guzzle.client:
        class: GuzzleHttp\Client

    AppBundle\Service\GeoClient:
        arguments:
            - '@guzzle.client'
            - '%mapbox_token%'

    AppBundle\DataflowType\Writer\MultipleContentStructureWriter:
        arguments:
            $contentStructureWriter: '@CodeRhapsodie\EzDataflowBundle\Writer\ContentWriter'

    rss.reader:
        class: SimplePie

    short_article.deleter:
        class: AppBundle\Service\ContentDeleter
        arguments:
            $contentTypeIdentifier: 'short_news'

    AppBundle\DataflowType\ArticleDataflow:
        arguments:
            $articleDeleter: '@short_article.deleter'

    AppBundle\DataflowType\TwitterDataflow:
        arguments:
            $twitDeleter: '@social_media_message.deleter'

    social_media_message.deleter:
        class: AppBundle\Service\ContentDeleter
        arguments:
            $contentTypeIdentifier: 'social_media_message'

    twitter.client:
        class: TwitterAPIExchange
        arguments:
            - {oauth_access_token: '%twitter_token_key%', oauth_access_token_secret: '%twitter_token_secret%', consumer_key: '%twitter_api_key%', consumer_secret: '%twitter_api_secret%'}