ezpublish:
  system:
    site:
      content_view:
        full:
          home:
            controller: AppBundle\Controller\HomeController
            template: "@ezdesign/full/home.html.twig"
            match:
              Id\Location: 2
          folder:
            controller: AppBundle\Controller\FolderController
            template: "@ezdesign/full/folder.html.twig"
            match:
              Identifier\ContentType: "folder"
          city:
            template: "@ezdesign/full/city.html.twig"
            match:
              Identifier\ContentType: "city"
          short_news:
            template: "@ezdesign/full/short_news.html.twig"
            match:
              Identifier\ContentType: "short_news"
