ezpublish:
  system:
    site:
      content_view:
        full:
          home:
            controller: AppBundle\Controller\HomeController
            template: "@ezdesign/full/home.html.twig"
            match:
              Id\Location: 2
